trigger:
  - main

variables:
  NODE_VERSION: '18.x'
  # Add feed variables
  npm_config_registry: 'https://pkgs.dev.azure.com/certstarorg/_packaging/az400-npm-feed/npm/registry/'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NODE_VERSION)
  displayName: 'Install Node.js'

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- script: |
    npm install
    npm install -g mocha
    npm install mochawesome
  displayName: 'Install Dependencies'

- script: |
    node app.js & sleep 5
    npm test -- --reporter mochawesome
    kill %1
  displayName: 'Start App and Run Tests'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/mochawesome.xml'
    mergeTestResults: true
    testRunTitle: 'Mocha Tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    exclude: |
      node_modules/**
      test/**
      .git/**
  displayName: 'Archive Build'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish Build Artifacts'

# Add package publishing step
- script: |
    npm version patch
    npm publish --registry=https://pkgs.dev.azure.com/certstarorg/_packaging/az400-npm-dev/npm/registry/
  displayName: 'Publish to Development Feed'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
