trigger: none # Manual trigger only

parameters:
- name: packageVersion
  type: string
  displayName: 'Package Version to Promote'
- name: environment
  type: string
  displayName: 'Target Environment'
  default: 'prod'
  values:
  - prod

variables:
- group: npm-publish-variables

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- script: |
    # Download from dev feed
    npm install @certstarorg/node-express-azure@${{ parameters.packageVersion }} --registry=https://pkgs.dev.azure.com/certstarorg/_packaging/az400-npm-dev/npm/registry/
    
    # Run validation tests
    npm test
  displayName: 'Download and Validate Package'

- task: ManualValidation@0
  inputs:
    notifyUsers: '$(approverEmail)'
    instructions: 'Please validate package version ${{ parameters.packageVersion }} before promotion to ${{ parameters.environment }}'

- script: |
    # Publish to production feed
    npm publish --registry=https://pkgs.dev.azure.com/certstarorg/_packaging/az400-npm-${{ parameters.environment }}/npm/registry/
  displayName: 'Promote Package'
  condition: succeeded()
