name: Push to GitHub

on:
  # Manual trigger
  workflow_dispatch:
  # Optional: Automatically push on changes to main
  push:
    branches:
      - main

jobs:
  push-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to target repository
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git remote add target https://${{ secrets.PUSH_TOKEN }}@github.com/timothywarner/nodeapp.git
          git push --force target HEAD:main
